UMC-AboutMe/AboutMe-BE

src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java, src/main/java/com/example/aboutme/app/controller/ProfileController.java, src/main/java/com/example/aboutme/app/dto/ProfileRequest.java, src/main/java/com/example/aboutme/app/dto/ProfileResponse.java, src/main/java/com/example/aboutme/converter/ProfileConverter.java, src/main/java/com/example/aboutme/converter/ProfileFeatureConverter.java, src/main/java/com/example/aboutme/domain/Profile.java, src/main/java/com/example/aboutme/domain/ProfileFeature.java, src/main/java/com/example/aboutme/repository/MemberRepository.java, src/main/java/com/example/aboutme/repository/ProfileRepository.java, src/main/java/com/example/aboutme/service/MemberService/MemberService.java, src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
#14
- 마이프로필 생성 API 구현
- memberId는 임시로 헤더로 받음
- 마이프로필 생성
=> #14 마이프로필 생성 API 구현완료

src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java, src/main/java/com/example/aboutme/app/controller/ProfileController.java, src/main/java/com/example/aboutme/app/dto/ProfileRequest.java, src/main/java/com/example/aboutme/app/dto/ProfileResponse.java, src/main/java/com/example/aboutme/converter/ProfileConverter.java, src/main/java/com/example/aboutme/converter/ProfileFeatureConverter.java, src/main/java/com/example/aboutme/domain/Profile.java, src/main/java/com/example/aboutme/domain/ProfileFeature.java, src/main/java/com/example/aboutme/repository/MemberRepository.java, src/main/java/com/example/aboutme/repository/ProfileRepository.java, src/main/java/com/example/aboutme/service/MemberService/MemberService.java, src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
#16 
- 마이프로필 조회 API 구현
- 마이페이지 조회
=> #16 마이프로필 조회 API 구현 완료

src/main/java/com/example/aboutme/app/controller/SpaceController.java, src/main/java/com/example/aboutme/app/dto/SpaceResponse.java, src/main/java/com/example/aboutme/converter/SpaceConverter.java, src/main/java/com/example/aboutme/repository/SpaceRepository.java, src/main/java/com/example/aboutme/service/SpaceService/SpaceQueryService.java, src/main/java/com/example/aboutme/service/SpaceService/SpaceQueryServiceImpl.java, src/main/java/com/example/aboutme/service/SpaceService/SpaceService.java, src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java, src/main/resources/application.yml
=> #22 마이스페이스 조회

.github/workflows/dev-deploy.yaml
=> #25 브랜치 변경

.github/workflows/dev-deploy.yaml
=> #25 javaVersion

.github/workflows/dev-deploy.yaml
=> #26 애플리케이션 이름

.github/workflows/dev-deploy.yaml
=> #35 deploy.yaml 문제 해결

src/main/java/com/example/aboutme/app/controller/RootController.java
=> #39 feat: health api 추가

src/main/java/com/example/aboutme/app/controller/ProfileController.java
- 가나(@choign3123)가 작성한 api에 대해서만 우선 수정후 테스트
- 헤더에는 언더스코어를 쓰면 안되나봄. 그래서 하이픈으로 변경
=> 헤더명 언더스코어->하이픈으로 변경

src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java, src/main/java/com/example/aboutme/app/controller/ProfileController.java, src/main/java/com/example/aboutme/app/dto/ProfileRequest.java, src/main/java/com/example/aboutme/app/dto/ProfileResponse.java, src/main/java/com/example/aboutme/converter/ProfileConverter.java, src/main/java/com/example/aboutme/domain/ProfileFeature.java, src/main/java/com/example/aboutme/repository/ProfileFeatureRepository.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java, src/main/java/com/example/aboutme/validation/annotation/ExistProfileFeature.java, src/main/java/com/example/aboutme/validation/validator/ProfileFeatureValidator.java
#49 
- 내 마이프로필 수정 API 구현 완료
- 마이프로필 수정
- 마이프로필 필수값인 이름에 빈값을 넣을시
- 해당하는 마이프로필가 없을 시
- 해당하는 마이프로필의 특징이 없을 시
=> #49 내 마이프로필 수정 API 구현 완료

src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
- #63
- 내 마이프로필 수정중 npe 발생
- key가 null일 수 있는걸 생각지 못하고 바로 .equals()를 호출해서 npe가 뜨는 것이었음
- .equals() 호출하기전 !=null 로 null체크 함
- 문제됐던 상황
=> #63 !긴급 내 마이프로필 수정시 발생하던 에러 해결

src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java, src/main/java/com/example/aboutme/app/controller/ProfileController.java, src/main/java/com/example/aboutme/app/dto/ProfileResponse.java, src/main/java/com/example/aboutme/converter/ProfileConverter.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
- #59 
- 내 마이프로필 단건 조회 API 구현
- 내 마이프로필 단건 조회
=> #59 내 마이프로필 단건 조회 API 구현완료

build.gradle, src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java, src/main/java/com/example/aboutme/aws/s3/S3Config.java, src/main/java/com/example/aboutme/aws/s3/S3Controller.java, src/main/java/com/example/aboutme/aws/s3/S3ResponseDto.java, src/main/java/com/example/aboutme/aws/s3/S3Service.java, src/main/resources/application.yml
- #61 
- S3 연결 : yml, S3Config, 환경변수 설정 (성호님께서 세팅하신 S3 버킷 및 IAM 액세스 키 연결했습니다.) 
- S3Controller, S3Service, S3ResponseDto 생성
- 개요란과 동일합니다.
- 파일 업로드 200
- 파일 업로드 400 : 요청 본문(key, key type, value) 오기입
- 파일 다운로드 200
- 파일 다운로드 404 : 버킷에 파일이 없는 경우(파일명 오기입)
- 로컬 환경변수 및 vm option 등록 필요합니다. (디스코드 참고)
=> #61 S3 파일 업로드 및 다운로드 API 구현

src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java, src/main/java/com/example/aboutme/validation/validator/ProfileFeatureValidator.java
#67 
- 빌드 에러 해결
- 프로필 특징이 없는건데, profile이 없다고 응답메시지가 가는 버그 해결
=> #67 빌드 에러 해결

src/main/java/com/example/aboutme/app/controller/LoginController.java, src/main/java/com/example/aboutme/app/dto/MsgResponse.java, src/main/java/com/example/aboutme/app/dto/SocialInfoRequest.java, src/main/java/com/example/aboutme/converter/LoginConverter.java, src/main/java/com/example/aboutme/converter/MemberConverter.java, src/main/java/com/example/aboutme/service/LoginService/GoogleService.java, src/main/java/com/example/aboutme/service/LoginService/GoogleServiceImpl.java, src/main/java/com/example/aboutme/service/LoginService/KakaoService.java, src/main/java/com/example/aboutme/service/LoginService/KakaoServiceImpl.java, src/main/java/com/example/aboutme/service/MemberService/MemberService.java, src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java
- delete Member구현
- Login 내부 파일 재구성
- delete Member구현
- Login 내부 파일 재구성
=> #79 delete Member구현 및 Login 내부 파일 재구성

src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java, src/main/java/com/example/aboutme/app/controller/LoginController.java, src/main/java/com/example/aboutme/app/dto/MemberProfileResponse.java, src/main/java/com/example/aboutme/app/dto/MsgResponse.java, src/main/java/com/example/aboutme/converter/LoginConverter.java, src/main/java/com/example/aboutme/converter/MemberConverter.java, src/main/java/com/example/aboutme/converter/MemberProfileConverter.java, src/main/java/com/example/aboutme/repository/MemberRepository.java, src/main/java/com/example/aboutme/service/LoginService/GoogleService.java, src/main/java/com/example/aboutme/service/LoginService/GoogleServiceImpl.java, src/main/java/com/example/aboutme/service/LoginService/KakaoService.java, src/main/java/com/example/aboutme/service/LoginService/KakaoServiceImpl.java, src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileServiceImpl.java
- 로그인 로직 변경, accesstoken을 프론트로부터 받아옴
- 기존의 이메일만 같고 소셜이 달라도 DB에 회원 저장이 되지 않는 문제 해결
- 백엔드로직으로 access token을 얻는 것이 아닌 프론트 자체적으로 얻은 토큰을 받아와 jwt토큰 발급
- saveMember하는 로직 변경
=> #81 Login Logic 추가

src/main/java/com/example/aboutme/converter/SpaceImageConverter.java, src/main/java/com/example/aboutme/domain/Space.java, src/main/java/com/example/aboutme/domain/SpaceImage.java, src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
=> #86 마이스페이스 이미지 디비 저장

src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java, src/main/java/com/example/aboutme/app/controller/SpaceController.java, src/main/java/com/example/aboutme/service/SpaceService/SpaceService.java, src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
=> #89 마이스페이스 생성 중복 확인

src/main/java/com/example/aboutme/apiPayload/exception/ExceptionAdvice.java, src/main/java/com/example/aboutme/apiPayload/exception/GeneralException.java
- #69 
- GeneralException 발생시 로그를 통해 어떤 문제인지 알 수 있도록 로그 작성
- 기존에는 GeneralException 발생시 로그가 남지 않았음. 지금은 로그 남음
- 이건 프론트랑 소통할 때 좋을 것 같아서 pr 올리는데, 필요없다 생각되면 close해도 괜찮습니당!
=> #69 서버 로그 방식 수정

src/main/java/com/example/aboutme/domain/Profile.java
=> #76 내 마이프로필 삭제시 발생하는 에러 해결

src/main/java/com/example/aboutme/converter/SpaceConverter.java, src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java
=> #93 마이스페이스 멤버 FK 미설정 오류 수정

src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java, src/main/java/com/example/aboutme/app/controller/ProfileController.java, src/main/java/com/example/aboutme/app/dto/ProfileRequest.java, src/main/java/com/example/aboutme/app/dto/ProfileResponse.java, src/main/java/com/example/aboutme/converter/ProfileConverter.java, src/main/java/com/example/aboutme/converter/ProfileImageConverter.java, src/main/java/com/example/aboutme/domain/Profile.java, src/main/java/com/example/aboutme/domain/ProfileImage.java, src/main/java/com/example/aboutme/domain/constant/ProfileImageType.java, src/main/java/com/example/aboutme/repository/ProfileImageRepository.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java, src/main/java/com/example/aboutme/validation/annotation/CheckEnumType.java, src/main/java/com/example/aboutme/validation/validator/EnumValidator.java
- #78 
- 내 마이프로필 이미지 수정하기 구현
- 이미지 변경에 따른 다른 api(내 마이프로필 조회 [단건, 목록])의 응답 수정
- 정상 응답
```
{
"isSuccess": true,
"code": "COMMON200",
"message": "성공입니다.",
"result": {
"type": "CHARACTER",
"characterType": 5,
"profile_image_url": null
}
}
혹은
{
"isSuccess": true,
"code": "COMMON200",
"message": "성공입니다.",
"result": {
"type": "USER_IMAGE",
"characterType": null,
"profile_image_url": "https://aboutme-bucket.s3.ap-northeast-2.amazonaws.com/f759ddc4-2db5-43db-906a-947e1ada433d.png"
}
}
혹은
{
"isSuccess": true,
"code": "COMMON200",
"message": "성공입니다.",
"result": {
"type": "DEFAULT",
"characterType": null,
"profile_image_url": null
}
}
``` 
- 오류 응답
```
{
"isSuccess": false,
"code": "PROFILE401",
"message": "해당하는 프로필이 존재하지 않습니다"
}
```
```
{
"isSuccess": false,
"code": "IMAGE401",
"message": "프로필 이미지는 …
```
=> #78 내 마이프로필 이미지 수정하기 API 완료

src/main/java/com/example/aboutme/app/controller/MemberProfileController.java, src/main/java/com/example/aboutme/app/dto/MemberProfileResponse.java, src/main/java/com/example/aboutme/app/dto/MemberSpaceResponse.java, src/main/java/com/example/aboutme/converter/MemberProfileConverter.java, src/main/java/com/example/aboutme/converter/ProfileConverter.java, src/main/java/com/example/aboutme/repository/MemberProfileRepository.java, src/main/java/com/example/aboutme/repository/ProfileFeatureRepository.java, src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileService.java, src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileServiceImpl.java
- #91 
- 프로필 보관함 내 검색(프로필 이름 바탕으로 목록 조회) 기능 구현했습니다.
```json
{
"isSuccess": true,
"code": "COMMON200",
"message": "성공입니다.",
"result": {
"memberProfileList": [
{
"profileId": 28,
"profileName": "아저씨",
"favorite": false,
"image": {
"type": "CHARACTER",
"characterType": 1,
"profile_image_url": null
}
},
{
"profileId": 31,
"profileName": "아기사자",
"favorite": true,
"image": {
"type": "USER_IMAGE",
"characterType": null,
"profile_image_url": "https://aboutme-bucket.s3.ap-northeast-2.amazonaws.com/a0087353-19c5-4cfa-b6b4-64a20386cc7d.jpeg"
}
},
{
"profileId": 33,
"profileName": "아가씨",
"favorite": false,
"image": {
"type": "DEFAULT",
"characterType": null,
"profile_image_url": null
}
}
]
}
}
```
=> #91 프로필 보관함 내 검색

src/main/java/com/example/aboutme/app/controller/ProfileController.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
- #100 
- 상대방 마이프로필 조회가 가능하도록 마이프로필 조회 API를 수정합니다.
- 프로필 주인 여부를 확인하는 로직 제거
- profile-id만 알고 있으면 누구나 해당 프로필 조회 가능
=> #100 상대방 마이프로필 조회

src/main/java/com/example/aboutme/app/controller/MemberProfileController.java
#98 
- MemberProfileController 전체 멤버 프로필 조회 반환값 통일을 위한 변경
- 동일한 클래스 내의 유은님의 searchMemberProfileList를 참고
MemberProfileController 전체 멤버 프로필 조회 반환값 통일을 위한 변경
=> update/멤버프로필스토리지 전체 조회 반환값 변경

src/main/java/com/example/aboutme/app/controller/ProfileController.java, src/main/java/com/example/aboutme/app/dto/ProfileResponse.java, src/main/java/com/example/aboutme/converter/ProfileConverter.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java, src/main/java/com/example/aboutme/validation/annotation/ExistProfileBySerialNum.java, src/main/java/com/example/aboutme/validation/validator/ProfileExistBySerialNumValidator.java
- #92 
- 마이프로필 검색 api 구현
- 정상 응답
```
{
"isSuccess": true,
"code": "COMMON200",
"message": "성공입니다.",
"result": {
"profile_id": 2,
"serial_number": 868768,
"profile_image": {
"type": "CHARACTER",
"characterType": 5,
"profile_image_url": null
},
"front_features": [
{
"key": "name",
"value": "최가나",
"feature_id": 8
}
]
}
}
```
- 오류 응답
```
{
"isSuccess": false,
"code": "PROFILE401",
"message": "해당하는 프로필이 존재하지 않습니다"
}
```
=> #92 마이프로필 검색 API 완료

src/main/java/com/example/aboutme/Login/jwt/TokenProvider.java, src/main/java/com/example/aboutme/app/controller/LoginController.java, src/main/java/com/example/aboutme/app/dto/SocialInfoRequest.java, src/main/java/com/example/aboutme/service/LoginService/KakaoServiceImpl.java, src/main/resources/application.yml
#97 
- 로그인 관련 편의를 위한 코드 수정
- jwt 토큰 유효 기간 변경
- jwt secret yml로 위치 변경
- 추가로 토큰 발급한 멤버 등록하였습니다.
- 프론트 요청에 따른 로직 추가
=> #97/login code update

src/main/java/com/example/aboutme/app/controller/MemberProfileController.java
=> #116 로깅 메세지 추가

src/main/java/com/example/aboutme/app/controller/ProfileController.java, src/main/java/com/example/aboutme/repository/ProfileRepository.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
#114 
- 프로필의 default값을 False로 하는 로직 추가
프로필의 default값을 False로 하는 로직 추가
=> #114 default값을 False로 하는 로직 추가

src/main/java/com/example/aboutme/repository/MemberProfileRepository.java
=> #128 merge conflict resolve

src/main/java/com/example/aboutme/app/controller/SpaceController.java, src/main/java/com/example/aboutme/repository/MemberRepository.java, src/main/java/com/example/aboutme/service/MemberService/MemberService.java, src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java
=> #127 마이스페이스 jwttoken으로 변경

src/main/java/com/example/aboutme/converter/ProfileConverter.java, src/main/java/com/example/aboutme/domain/ProfileImage.java
- #122 
- 프로필 이미지를 함께 조회하는 모든 api에서 type=none일 때 character값을 같이 주는 문제가 있었음.
=> #122 프로필 이미지 응답값 에러 수정

src/main/java/com/example/aboutme/domain/mapping/MemberSpace.java
- #105
- MemberSpace 엔티티가 BaseEntity를 미상속받고 있었음.
=> MemberSpace 엔티티가 BaseEntity 미상속받던 것 수정

src/main/java/com/example/aboutme/app/controller/AlarmController.java, src/main/java/com/example/aboutme/app/dto/AlarmResponse.java, src/main/java/com/example/aboutme/converter/AlarmConverter.java, src/main/java/com/example/aboutme/domain/Alarm.java, src/main/java/com/example/aboutme/repository/AlarmRepository.java, src/main/java/com/example/aboutme/service/AlarmService/AlarmService.java, src/main/java/com/example/aboutme/service/AlarmService/AlarmServiceImpl.java, src/main/resources/application.yml
- #120 
- 알림 데이터(프로필 / 스페이스 공유)를 조회합니다.
- 프로필 공유 알림은 profile_serial_number, 스페이스 공유 알림은 space_id에 값을 넣어줍니다.
```json
{
"isSuccess": true,
"code": "COMMON200",
"message": "성공입니다.",
"result": {
"alarms": [
{
"content": "훈이님이 프로필을 공유하셨습니다",
"profile_serial_number": 180120,
"space_id": null
},
{
"content": "유리님이 프로필을 공유하셨습니다",
"profile_serial_number": 314172,
"space_id": null
},
{
"content": "철수님이 스페이스를 공유하셨습니다",
"profile_serial_number": null,
"space_id": 3
}
]
}
}
```
- Alarm 엔티티에 Profile, Space 추가했습니다.
- 위 변경사항 반영이 필요하여 임시로 스페이스 공유와 관련된 코드 수정했습니다.
=> #120 알림 데이터 조회

src/main/java/com/example/aboutme/converter/MemberProfileConverter.java, src/main/java/com/example/aboutme/converter/MemberSpaceConverter.java
- #130 
- 프로필 보관함, 아지트 목록 조회시 즐겨찾기한 요소들을 우선 정렬합니다.
=> #130 즐겨찾기 우선 정렬

src/main/java/com/example/aboutme/converter/AlarmConverter.java
=> fix: merge conflict resolve

src/main/java/com/example/aboutme/app/controller/MyPageController.java, src/main/java/com/example/aboutme/app/controller/ProfileController.java, src/main/java/com/example/aboutme/repository/MemberRepository.java, src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileService.java, src/main/java/com/example/aboutme/service/MemberProfileService/MemberProfileServiceImpl.java, src/main/java/com/example/aboutme/service/MemberService/MemberService.java, src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileService.java, src/main/java/com/example/aboutme/service/ProfileService/ProfileServiceImpl.java
- #136 
- 헤더 member-id -> token으로 변경
=> 헤더 member-id -> token 으로 변경

src/main/java/com/example/aboutme/Login/jwt/TokenProvider.java, src/main/java/com/example/aboutme/app/controller/AlarmController.java, src/main/java/com/example/aboutme/app/controller/MemberProfileController.java, src/main/java/com/example/aboutme/app/controller/MemberSpaceController.java, src/main/java/com/example/aboutme/app/controller/ProfileController.java, src/main/java/com/example/aboutme/repository/MemberRepository.java, src/main/java/com/example/aboutme/service/MemberService/MemberService.java, src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java
=> #139 토큰 방식으로 변경

src/main/java/com/example/aboutme/Login/jwt/TokenProvider.java, src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java
- #143 
- 동등성(equals) 비교가 아닌 동일성(==) 비교를 해서 문제가 발생했던 것이었음.
=> #143 tokenProvider 잘못된 소셜타입 리턴하던 에러 해결

src/main/java/com/example/aboutme/repository/ProfileFeatureRepository.java, src/main/java/com/example/aboutme/service/MemberService/MemberServiceImpl.java
- #140
- 프로필을 한개도 만들지 않았을 때 마이페이지 조회시 length error 뜨는 문제 해결
=> #140 마이페이지 조회 에러 수정

src/main/java/com/example/aboutme/app/controller/MemberProfileController.java
#147 
- getMyProfilesStorage 인자 수정
- getMyProfilesStorage 인자 수정
=> #147 MemberProfileController 수정

.github/workflows/dev-deploy.yaml, .platform/nginx/conf.d/client_max_body_size.conf, src/main/resources/application.yml
=> #149 cicd 다시 배포

src/main/java/com/example/aboutme/apiPayload/code/status/ErrorStatus.java, src/main/java/com/example/aboutme/app/controller/SpaceController.java, src/main/java/com/example/aboutme/app/dto/SpaceRequest.java, src/main/java/com/example/aboutme/domain/Alarm.java, src/main/java/com/example/aboutme/repository/SpaceRepository.java, src/main/java/com/example/aboutme/service/SpaceService/SpaceServiceImpl.java, src/main/java/com/example/aboutme/validation/annotation/ExistSpaceNickname.java, src/main/java/com/example/aboutme/validation/validator/SpaceNicknameExistValidator.java
=> #152 my space share update
